---
general:
  host: "localhost"
  port: 9999
  frame_source:
    type: "oakd_xlink"
    parameters:
      stream_color_video: True
      stream_depth_video: True
      stream_body: True
      streaming_color_format: "COLOR_BGRA32"
      streaming_color_resolution: "COLOR_RESOLUTION_720P"
      streaming_depth_mode: "STEREO_DISPARITY"
      streaming_depth_resolution: "STEREO_RESOLUTION_480P"
      streaming_rate: "30"
video_encoder:
  0: #color
    type: "null"
  1: #depth
    type: "null"
  4: #object-human
    type: "null"